config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:'projects#index'
  resources :projects, only: [:new, :create, :index,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  enum demand: { face_to_face: 1, remote: 2 }
  validates :maximum_value_hour, numericality: { greater_than_or_equal_to:0 }
  validates :title,:description,:skills_descritions,:maximum_value_hour,:demand,:deadline, presence:  true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    # Render 404 page when record not found
      def render_404      
        render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found
      end
  end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    id = params[:id]
    @project = Project.find(id)
    render layout: "user"
  end

  def index
    @projects = Project.all

    render layout: "user"
  end

  def new
    @project = Project.new
    render layout: "user"
  end

  def create
    @project = Project.create(params.require(:project).permit(:title,:description,:skills_descritions,:maximum_value_hour,:demand,:deadline))
    
      if @project.save 
        redirect_to @project
      else
          render :new,layout: "user"
      end  
  end
  
 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeEasy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FreeEasy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'responsive_header' %>
    <%= stylesheet_link_tag 'user' %>
    <%= stylesheet_link_tag 'card' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%# MENU %>
    <div class="header">
        <a href="#default" class="logo"> Free<strong>Easy</strong></a>
        <div class="header-right">
            <a href="#home">Home</a>
  
            <div class="dropdown">
            <button class="dropbtn">Projetos
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="<%= new_project_path %>">Cadastrar</a>
              <a href="#">Buscar</a>
              <a href="#">Propostas</a>
            </div>
          </div>

            <a href="#about">About</a>
            
        </div>

    </div>
    <%# MENU %>
    <div class="contante-main">
        <%= yield %>
    </div>
  </body>
</html>

app/views/projects/index.html.erb
<% if !@projects.blank? %>
  <% for t in @projects %>    
    <div id="container" class="box effect2" onclick="(window.location='<%= project_path(t) %>')">
        <h3><span>  <%= t.title %></span> <i>6 dias atrás</i></h3>
        <p> <%= t.description %> </p>

        <ul>
            <li><strong>Habilidades Desejadas:</strong> <%= t.skills_descritions %></li>
            <li><strong>Valor:</strong><%= number_to_currency(t.maximum_value_hour, unit: 'R$', separator:',' , format:"%u %n") %>/Hrs</li>
            <li><strong>Demanda:</strong> <%= t.demand %></li>
            <li><strong>Prazo Final:</strong> <%= t.deadline %></li>
        </ul>
        
        <%= link_to 'Veja mais' ,t %>

        <div class="borda"></div>
    </div>
  <% end %>
<% else %>
 <h1>Nem um projeto cadastrado ainda</h1>
<% end %>

app/views/projects/new.html.erb
<h1>ooioi</h1>

<% if @project.errors.any? %>
    <ul>
        <% @project.errors.full_messages.each do |error| %>
            <li> <%= error %> </li>
        <% end %>    
    </ul>
<% end %>

<%= form_for @project do |f| %>
  <%= f.label :title, 'Título' %>
  <%= f.text_field :title %>   

   <%= f.label :description, 'Descrição' %>
  <%= f.text_field :description %>   

   <%= f.label :skills_descritions, 'Descreva as Habilidades Esperadas' %>
  <%= f.text_area :skills_descritions %>   

   <%= f.label :maximum_value_hour, 'valor máximo (por hora de trabalho)' %>
  <%= f.number_field :maximum_value_hour %>

  <%= f.label :deadline, 'Data limite' %>
  <%= f.date_field :deadline     %>

 <%= f.label :demand %>
 <%= f.select :demand, options_for_select(Project.demands.map { |key, value| [key.humanize, key] }), {prompt: "Select Type of Property..."}, class: "form-control" %>
 
 <%= f.submit 'Enviar' %>

  

  
<% end %>

app/views/projects/show.html.erb
<% if !@project.blank? %> 
    <div id="container" >
        <h3><span>  <%= @project.title %></span> <i>6 dias atrás</i></h3>
        <p> <%= @project.description %> </p>

        <ul>
            <li><strong>Habilidades Desejadas:</strong> <%= @project.skills_descritions %></li>
            <li><strong>Valor:</strong><%= number_to_currency(@project.maximum_value_hour, unit: 'R$', separator:',' , format:"%u %n") %>/Hrs</li>
            <li><strong>Demanda:</strong> <%= @project.demand %></li>
            <li><strong>Prazo Final:</strong> <%= @project.deadline %></li>
        </ul>
        
         <%= link_to 'Voltar' ,root_path %> 

        <div class="borda"></div>
    </div>
  
<% else %>
 <h1>Projeto Não existe</h1>
<% end %>